import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
import { supabase, supabaseConfigured } from "./lib/supabaseClient";

const owner="skijajahmadstudio@gmail.com";
const initial=[{id:1,merchant:"Grocery",category:"Food",amount:1450,date:"2026-09-28"},{id:2,merchant:"Transport",category:"Transport",amount:620,date:"2026-09-27"},{id:3,merchant:"Online Shopping",category:"Shopping",amount:1890,date:"2026-09-25"},{id:4,merchant:"Electricity",category:"Bills",amount:980,date:"2026-09-22"}];
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);

function App(){
 const[session,setSession]=useState(null);
 const[tab,setTab]=useState("home"),[income]=useState(42000),[expenses,setExpenses]=useState(initial),[coins,setCoins]=useState(18400),[premium]=useState(false),[question,setQuestion]=useState(""),[chat,setChat]=useState([{role:"ai",text:"Hello! I’m your AI Financial Friend. Tell me what you spent today or ask where you can save."}]),[toast,setToast]=useState("");
 useEffect(()=>{if(!supabaseConfigured)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 const total=expenses.reduce((s,e)=>s+e.amount,0),savings=Math.max(income-total,0);
 const cats=useMemo(()=>expenses.reduce((a,e)=>(a[e.category]=(a[e.category]||0)+e.amount,a),{}),[expenses]);
 const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];
 const notify=t=>{setToast(t);setTimeout(()=>setToast(""),2500)};
 const addExpense=()=>{const amount=Number(prompt("Expense amount (₹)")||0);if(!amount)return;const merchant=prompt("What was it for?")||"Expense";setExpenses(x=>[{id:Date.now(),merchant,category:"Other",amount,date:new Date().toISOString().slice(0,10)},...x]);setCoins(x=>Math.min(50000,x+250));notify("Expense added • 250 coins credited for AI review")};
 const askAI=()=>{if(!question.trim())return;const limit=premium?100:30;if(chat.filter(x=>x.role==="user").length>=limit)return notify("Daily AI question limit reached.");let answer=`Your recorded expenses are ${money(total)} and estimated savings are ${money(savings)}.`;const q=question.toLowerCase();if(q.includes("save")||q.includes("reduce"))answer=`Your highest recorded category is ${top?top[0]:"Other"} at ${money(top?top[1]:0)}. Consider setting a weekly cap and reviewing non-essential purchases before paying.`;setChat(x=>[...x,{role:"user",text:question},{role:"ai",text:answer}]);setQuestion("")};
 const nav=[["home","Home"],["expenses","Expenses"],["challenge","Challenge"],["rewards","Rewards"],["live","Live"],["profile","Profile"],["admin","Admin"]];
 return <div className="app">
  <header><div className="brand"><div className="logo">MS</div><div><b>Money Save</b><small>Save • Secure • Grow</small></div></div><div className="headerMeta"><span className={premium?"badge premium":"badge"}>{premium?"PREMIUM":"FREE"}</span><span>🪙 {coins.toLocaleString()}</span>{supabaseConfigured&&session&&<button className="signout" onClick={()=>supabase.auth.signOut()}>Sign out</button>}</div></header>
  <main>{supabaseConfigured&&!session&&<section className="authGate"><div className="panel authCard"><label>SECURE ACCOUNT</label><h1>Sign in to Money Save</h1><p>Use your email to continue. Your finance data is protected behind authenticated access.</p><button onClick={async()=>{const email=prompt("Enter your email");if(!email)return;const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});notify(error?error.message:"Check your email for the secure sign-in link.")}}>Send secure login link</button><small>Google sign-in will be enabled through the authentication provider configuration.</small></div></section>}
   {tab==="home"&&<section className="page"><div className="hero"><div><label>GOOD MONEY HABITS</label><h1>Make every rupee count.</h1><p>Save your money, secure it, and watch your future savings grow.</p></div><button onClick={addExpense}>+ Add Expense</button></div>
    <div className="cards">{[["Total income",money(income),"This month"],["Total expenses",money(total),expenses.length+" recorded items"],["Estimated savings",money(savings),Math.round(savings/income*100)+"% savings rate"],["Savings goal",Math.min(100,Math.round(savings/30000*100))+"%","Goal ₹30,000"]].map(x=><div className="card"><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></div>)}</div>
    <div className="cols"><div className="panel"><div className="panelTitle"><h2>AI Financial Friend</h2><em>● Online</em></div><div className="chat">{chat.slice(-5).map((m,i)=><div className={"msg "+m.role} key={i}>{m.text}</div>)}</div><div className="ask"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&askAI()} placeholder="Ask about your money…"/><button onClick={askAI}>Ask</button></div><small className="hint">{premium?"100":"30"} AI questions/day</small></div>
    <div className="panel"><div className="panelTitle"><h2>Spending insight</h2><span className="pill">AI</span></div><div className="insight"><div className="ring">{top?Math.round(top[1]/total*100):0}%</div><div><b>{top?top[0]:"No data yet"}</b><p>Your highest recorded spending category. Review non-essential purchases here first.</p></div></div><hr/><h3>Daily check-in</h3><p>How much did you spend today, and what was it for?</p><button className="secondary" onClick={addExpense}>Log today’s spending</button></div></div>
   </section>}
   {tab==="expenses"&&<section className="page"><div className="titleRow"><div><label>TRACK</label><h1>Expense Tracker</h1></div><button onClick={addExpense}>+ Add expense</button></div><div className="panel">{expenses.map(e=><div className="expense"><div><b>{e.merchant}</b><small>{e.category} • {e.date}</small></div><strong>{money(e.amount)}</strong></div>)}</div><div className="panel scanner"><div><span className="pill">RECEIPT SCANNER</span><h2>Turn receipts into expenses</h2><p>AI extracts merchant, date, items, category and total, then asks you to confirm before saving.</p></div><button className="secondary" onClick={()=>notify("Receipt Scanner is ready for OCR + secure storage integration.")}>Scan receipt</button></div></section>}
   {tab==="challenge"&&<section className="page"><label>AI SAVINGS CHALLENGE</label><h1>Build a saving habit.</h1><div className="panel challenge"><div className="check">✓</div><div className="grow"><h2>7-Day Smart Spending Challenge</h2><p>Log spending daily, avoid one unnecessary purchase, and keep your weekly cap.</p><div className="progress"><i/></div><small>4 of 7 days completed</small></div><button onClick={()=>{setCoins(x=>x+500);notify("Challenge activity recorded • 500 coins added for review")}}>Log today</button></div><div className="cols"><div className="panel"><h2>Coin rules</h2><p>AI reviews positive financial activity and records a reason for each award.</p><ul><li>30,000 coins → ₹10 eligibility</li><li>50,000 coins → ₹30 eligibility</li><li>Above 50,000 → no additional cash tier</li></ul></div><div className="panel"><h2>Your coins</h2><strong className="big">{coins.toLocaleString()}</strong><p>Next reward tier at 30,000</p></div></div></section>}
   {tab==="rewards"&&<section className="page"><label>REWARDS</label><h1>Reward & verification</h1><div className="cols"><div className="panel"><h2>30,000 coins</h2><strong className="reward">₹10</strong><p>Subject to eligibility, verification and Rewards Policy.</p></div><div className="panel"><h2>50,000 coins</h2><strong className="reward">₹30</strong><p>Payment is not guaranteed; anti-fraud and bank verification apply.</p></div></div><div className="panel"><h2>Claim workflow</h2><div className="steps"><span>1 Submitted</span><span>2 Verified</span><span>3 Paid</span></div><button className="secondary" onClick={()=>notify("Verification form: bank account, IFSC, holder name and bank proof.")}>Start verification</button></div></section>}
   {tab==="live"&&<section className="page"><label>LIVE MEETING GATEWAY</label><h1>Learn from top savers.</h1><div className="live"><div className="video"><span>LIVE</span><b>Live session player</b><small>10:00–10:30 AM • 8:00–8:30 PM</small></div><div className="panel"><h2>Today’s sessions</h2><p>Hosts can be selected from respected top contributors. Exact savings amounts are never shown publicly.</p><p>Free: 10 min/day • Premium: 30 min/day</p><button onClick={()=>notify("Live viewer opened. Video provider integration comes next.")}>Join live</button></div></div></section>}
   {tab==="profile"&&<section className="page"><label>ACCOUNT</label><h1>Your profile</h1><div className="panel profile"><div className="avatar">MS</div><div><h2>Money Save User</h2><p>User ID: <b>MS-USER-000001</b></p><span className="badge">FREE USER</span></div></div><div className="panel"><h2>Upgrade to Premium</h2><p>Premium raises AI questions from 30/day to 100/day and unlocks advanced analysis features.</p><button onClick={()=>notify("Premium payment flow is prepared for PhonePe QR + screenshot review.")}>Upgrade</button></div></section>}
   {tab==="admin"&&<section className="page"><label>OWNER CONTROL</label><h1>Admin Command Center</h1><div className="notice">Owner account: <b>{owner}</b></div><div className="cards">{["Users","Payments","Rewards","Moderation"].map(x=><div className="card"><span>{x}</span><strong>—</strong><small>Control panel</small></div>)}</div><div className="panel"><h2>Security-first controls</h2><p>Server-side owner authorization, roles, audit logs, private payment documents, reward verification, suspicious-payment review and 24-hour restriction workflows are planned for the backend.</p></div></section>}
  </main>
  <nav>{nav.map(([id,name])=><button className={tab===id?"active":""} onClick={()=>setTab(id)}>{name}</button>)}</nav>{toast&&<div className="toast">{toast}</div>}
 </div>
}
createRoot(document.getElementById("root")).render(<App/>);